FROM node:alpine

WORKDIR /app

COPY package.json .

RUN apk update && apk upgrade && apk add --no-cache bash git openssh

RUN npm install

# COPY client directory folder
COPY . .

CMD ["npm","start"]